name: Mol_RL
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - ld_impl_linux-64=2.43
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - libnsl=2.0.1
  - libsqlite=3.47.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.3.2
  - pip=24.2
  - python=3.10.12
  - readline=8.2
  - setuptools=75.1.0
  - tk=8.6.13
  - wheel=0.44.0
  - xz=5.2.6
  - pip:
      - aiohappyeyeballs==2.4.3
      - aiohttp==3.10.10
      - aiosignal==1.3.1
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - async-timeout==4.0.3
      - attrs==24.2.0
      - certifi==2024.8.30
      - charset-normalizer==3.4.0
      - click==8.1.7
      - cloudpickle==3.1.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.2.1
      - docker-pycreds==0.4.0
      - einops==0.8.0
      - exceptiongroup==1.2.2
      - executing==2.2.0
      - fairscale==0.4.13
      - farama-notifications==0.0.4
      - filelock==3.16.1
      - fonttools==4.54.1
      - fpdf==1.7.2
      - frozenlist==1.5.0
      - fsspec==2024.10.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.29.1
      - idna==3.10
      - ipython==8.35.0
      - jedi==0.19.2
      - jinja2==3.1.4
      - joblib==1.4.2
      - kiwisolver==1.4.7
      - labml==0.4.168
      - labml-helpers==0.4.89
      - labml-nn==0.4.137
      - markupsafe==3.0.2
      - matplotlib==3.9.2
      - matplotlib-inline==0.1.7
      - mpmath==1.3.0
      - multidict==6.1.0
      - networkx==3.4.2
      - numpy==2.1.2
      - nvidia-cublas-cu12==12.4.5.8
      - nvidia-cuda-cupti-cu12==12.4.127
      - nvidia-cuda-nvrtc-cu12==12.4.127
      - nvidia-cuda-runtime-cu12==12.4.127
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.2.1.3
      - nvidia-curand-cu12==10.3.5.147
      - nvidia-cusolver-cu12==11.6.1.9
      - nvidia-cusparse-cu12==12.3.1.170
      - nvidia-nccl-cu12==2.21.5
      - nvidia-nvjitlink-cu12==12.4.127
      - nvidia-nvtx-cu12==12.4.127
      - packaging==24.1
      - pandas==2.2.3
      - parso==0.8.4
      - pexpect==4.9.0
      - pillow==11.0.0
      - platformdirs==4.3.6
      - prompt-toolkit==3.0.51
      - propcache==0.2.0
      - protobuf==5.29.1
      - psutil==6.1.0
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pydantic==2.10.3
      - pydantic-core==2.27.1
      - pygments==2.19.1
      - pyparsing==3.2.0
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - rdkit==2024.3.5
      - requests==2.32.3
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - six==1.16.0
      - smmap==5.0.1
      - stack-data==0.6.3
      - sympy==1.13.1
      - threadpoolctl==3.5.0
      - torch==2.5.1
      - torch-geometric==2.6.1
      - torch-scatter==2.1.2
      - -f https://data.pyg.org/whl/torch-2.5.1+cu124.html
      - torchtext==0.18.0
      - torchvision==0.20.1
      - tqdm==4.66.5
      - traitlets==5.14.3
      - triton==3.1.0
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.2.3
      - wandb==0.19.1
      - wcwidth==0.2.13
      - whittaker-eilers==0.1.3
      - yarl==1.16.0
